1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

In [10]:
l = [[1,2], [3,4]]

In [13]:
a  = np.array(l)
a

array([[1, 2],
       [3, 4]])

In [14]:
l1 = [[3,4], [5,6]]

In [15]:
b = np.array(l1)

In [16]:
b

array([[3, 4],
       [5, 6]])

In [18]:
def arr_add(matrix1, matrix2):
    c = matrix1 + matrix2
    return c

In [19]:
arr_add(a,b)

array([[ 4,  6],
       [ 8, 10]])

2. Write a Python Program to Multiply Two Matrices?

In [20]:
def arr_multiply(matrix1, matrix2):
    mul = matrix1 @ matrix2
    return mul

In [21]:
arr_multiply(a,b)

array([[13, 16],
       [29, 36]])

3. Write a Python Program to Transpose a Matrix?

In [24]:
def mat_transpose(matrix):
    return matrix.T

In [25]:
mat_transpose(b)

array([[3, 5],
       [4, 6]])

4. Write a Python Program to Sort Words in Alphabetic Order?

In [43]:
l = ['mumbai', 'delhi', 'karnataka', 'banglore']

In [44]:
l

['mumbai', 'delhi', 'karnataka', 'banglore']

In [45]:
def sorter(l):
    l.sort()
    return l

In [46]:
sorter(l)

['banglore', 'delhi', 'karnataka', 'mumbai']

5. Write a Python Program to Remove Punctuation From a String?

In [48]:
punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''


In [55]:
def remove_punctuations(string):
    new_str = ''
    for i in string:
        if i not in punc:
            new_str = new_str + i
    return new_str
    

In [56]:
remove_punctuations('mehul@#$')

'mehul'